---
title: "Bike Share Case Study"
author: "Andy Guo"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
library(tidyverse)
library(lubridate)
```

```{r}
bikedata1 <- list.files(pattern = "*.csv") %>% 
  lapply(read_csv) %>% 
  bind_rows()
```

```{r}
bikedata1 %>% count(member_casual)
```

```{r}
bikedata1$date <- as_date(bikedata1$started_at)
bikedata1$month <- format(as_date(bikedata1$date), "%m")
bikedata1$day <- format(as_date(bikedata1$date), "%d")
bikedata1$year <- format(as_date(bikedata1$date), "%Y")
bikedata1$day_of_week <- format(as_date(bikedata1$started_at), "%A")
```

```{r}
bikedata1$ride_length <- difftime(bikedata1$ended_at, bikedata1$started_at) %>% as_hms()
```

```{r}
cmini <- mini %>% select(-end_station_name, -end_station_id, -end_lat, -end_lng, -start_lat, -start_lng, -start_station_name, -start_station_id)
```

```{r}
summary(as.numeric(cmini$ride_length)) / 60
```

```{r}
aggregate(list(ride_length = cmini$ride_length), list(member_type = cmini$member_casual), mean)
```
